services:
  - type: web
    name: fraude-detection-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-summer-shadow-apullpsx-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_fFjHNhOg9Q3i