spring.application.name=fraude-detection
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-summer-shadow-apullpsx-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_fFjHNhOg9Q3i}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000

server.port=8080

