spring.application.name=fraude-detection
spring.datasource.url=jdbc:postgresql://ep-summer-shadow-apullpsx-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fFjHNhOg9Q3i

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

