apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraude-ingress
  namespace: fraude-detection
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fraude.example.com # replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
